#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))

from runtime_common import load_json, project_root


def release_dir(project: Path) -> Path:
    return project / '.zoo-agent' / 'release'


def bullet_list(items: list[Any], empty: str) -> list[str]:
    values = [str(item) for item in items if str(item or '').strip()]
    return [f'- {item}' for item in values] if values else [f'- {empty}']


def build_pr_draft(project: Path) -> dict[str, str]:
    plan = load_json(release_dir(project) / 'pr_plan.json')
    changed = plan.get('changed_areas') or []
    draft_only = not changed
    lines = [
        f'# {plan.get("pr_title") or "Local PR draft"}',
        '',
        '## Summary',
        str(plan.get('summary') or 'Local PR draft generated by the AI Project Operator.'),
    ]
    if draft_only:
        lines.extend(['', 'Draft only; no code changes included yet.'])
    lines.extend(
        [
            '',
            '## What changed',
            *bullet_list(changed, 'No changed files detected in this workflow.'),
            '',
            '## Why',
            '- Prepare the project for review using local Project Map, release readiness, and session evidence.',
            '',
            '## Evidence',
            *bullet_list(
                [json.dumps(item, ensure_ascii=False) for item in plan.get('evidence') or []],
                'Evidence is not available yet.',
            ),
            '',
            '## Test plan',
            *bullet_list(plan.get('test_plan') or [], 'Not run in this workflow'),
            '',
            '## Risks',
            f'- Risk level: {plan.get("risk_level") or "unknown"}',
            '',
            '## Rollback',
            *bullet_list(plan.get('rollback_plan') or [], 'Use local checkpoint or Git controls before publishing.'),
            '',
            '## Review focus',
            *bullet_list(plan.get('review_focus') or [], 'Review generated text against the actual diff.'),
            '',
            '## Not included',
            *bullet_list(plan.get('not_included') or [], 'Remote PR creation is not included in this local workflow.'),
            '',
        ]
    )
    path = release_dir(project) / 'pr_draft.md'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines), encoding='utf-8')
    return {'status': 'ok', 'pr_draft': '.zoo-agent/release/pr_draft.md', 'draft_only': str(draft_only).lower()}


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate a local GitHub PR draft.')
    parser.add_argument('--workspace', default='.')
    args = parser.parse_args()
    project = project_root(args.workspace)
    payload = build_pr_draft(project)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
